# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GcpSnapCrab < Formula
  desc "Minimalist, terminal-based tool to create and restore google cloud platform (g"
  homepage "https://github.com/ruteckimikolaj/gcp-snap-crab"
  url "https://github.com/ruteckimikolaj/gcp-snap-crab/archive/refs/tags/0.3.0.tar.gz"
  sha256 "b9f638ee25ae96935a06ffeafdd9f064da285c415a175719b299a201879519d5"
  license "NOASSERTION"

  on_macos do
    on_intel do
      url "https://github.com/ruteckimikolaj/gcp-snap-crab/releases/download/0.3.0/gcp-snap-crab-0.3.0-darwin-amd64.tar.gz"
      sha256 "b591019df9f55efd9844c8d1c13f4889748cb0168f7021548365d384f34738b1"
    end

    on_arm do
      url "https://github.com/ruteckimikolaj/gcp-snap-crab/releases/download/0.3.0/gcp-snap-crab-0.3.0-darwin-arm64.tar.gz"
      sha256 "1c0139b282296ea573429da2ddf7b92639529b55e50afd7c2a1bb06a62d25933"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ruteckimikolaj/gcp-snap-crab/releases/download/0.3.0/gcp-snap-crab-0.3.0-linux-amd64.tar.gz"
      sha256 "cc8b442c4ecf449782775421584731b03caa37068c0d3b5c33c3c70a2c9b23eb"
    end

    on_arm do
      url "https://github.com/ruteckimikolaj/gcp-snap-crab/releases/download/0.3.0/gcp-snap-crab-0.3.0-linux-arm64.tar.gz"
      sha256 "5f446c667e88c49782f4674c0a4d4bc6e9001e1d899d6480f0fccb087a06a480"
    end
  end

  def install
    bin.install "gcp-snap-crab"
  end

  test do
    assert_match version, shell_output("#{bin}/gcp-snap-crab --version")
  end
end
