# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pomodorust < Formula
  desc "Pomodoro app written in rust"
  homepage "https://github.com/ruteckimikolaj/pomodorust"
  url "https://github.com/ruteckimikolaj/pomodorust/archive/refs/tags/0.2.1.tar.gz"
  sha256 "86d6f52679d838a81a34f512d9954f150ade04fe73fb826f640a27ec4df4c660"
  license "NOASSERTION"

  on_macos do
    on_intel do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.1/pomodorust-0.2.1-darwin-amd64.tar.gz"
      sha256 "9057f0c6ca8315fe37471c1a1b51e271ce91dbb1002e82b9c10dc5e4cf0eeb99"
    end

    on_arm do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.1/pomodorust-0.2.1-darwin-arm64.tar.gz"
      sha256 "f9ea0683f93b42178978f340ad8cd56084b829a7b255af57704083034d9c38b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.1/pomodorust-0.2.1-linux-amd64.tar.gz"
      sha256 "a18614735a6416f7fdfee6cc2bdd26cef5cdc70feb59dcd7de31735a313380e0"
    end

    on_arm do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.1/pomodorust-0.2.1-linux-arm64.tar.gz"
      sha256 "86dd656a4fa20b7c2dcfcb606ab92a70789ecac14052d0d4010f081ccd8c7ea8"
    end
  end

  def install
    bin.install "pomodorust"
  end

  test do
    assert_match version, shell_output("#{bin}/pomodorust --version")
  end
end
