# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pomodorust < Formula
  desc "Pomodoro app written in rust"
  homepage "https://github.com/ruteckimikolaj/pomodorust"
  url "https://github.com/ruteckimikolaj/pomodorust/archive/refs/tags/0.2.0.tar.gz"
  sha256 "b6130dfc1a397508c858502beaf3ca8ef1f7f1f30a0daf2ec526685d00a71253"
  license "NOASSERTION"

  on_macos do
    on_intel do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.0/pomodorust-0.2.0-darwin-amd64.tar.gz"
      sha256 "5c3eee5955e761614e28c65982620833d2d57756d6d3134ae73a6f8e2ea46fed"
    end

    on_arm do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.0/pomodorust-0.2.0-darwin-arm64.tar.gz"
      sha256 "5132f9e30d4d504320f5b16e7c67685495e59996f8f89c5bb21439edaa4127a5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.0/pomodorust-0.2.0-linux-amd64.tar.gz"
      sha256 "41bc3c4d11012275f17dd872b948e5a3c39b5c8d0bacda2db723cd3f3e75a6f1"
    end

    on_arm do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.0/pomodorust-0.2.0-linux-arm64.tar.gz"
      sha256 "cfe8913644f08b0724038953a08fdea711bbc61036b56bcb315424f71937dd6a"
    end
  end

  def install
    bin.install "pomodorust"
  end

  test do
    assert_match version, shell_output("#{bin}/pomodorust --version")
  end
end
