# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pomodorust < Formula
  desc "Pomodoro app written in rust"
  homepage "https://github.com/ruteckimikolaj/pomodorust"
  url "https://github.com/ruteckimikolaj/pomodorust/archive/refs/tags/0.2.0.tar.gz"
  sha256 "b526899aed43d21c211f9887924abd206246b25ab5b381d97e768859e4d07871"
  license "NOASSERTION"

  on_macos do
    on_intel do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.0/pomodorust-0.2.0-darwin-amd64.tar.gz"
      sha256 "2eabbc8893a8003a9924aba120a3a1ce21016d3d6f31f74a4a39d61352562a9d"
    end

    on_arm do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.0/pomodorust-0.2.0-darwin-arm64.tar.gz"
      sha256 "72ddf9ba11cb3d378bfede7dddd6ca50016be014aa8560d1da5c1e577e38c714"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.0/pomodorust-0.2.0-linux-amd64.tar.gz"
      sha256 "d2159d78b85755a0ae502257b7a58f71aedf1d0e375b4cdfcbee593afb408e70"
    end

    on_arm do
      url "https://github.com/ruteckimikolaj/pomodorust/releases/download/0.2.0/pomodorust-0.2.0-linux-arm64.tar.gz"
      sha256 "985d4694f94d4b7feddd933f9c498a2bee8738932149ecb8184fc3ea6129d271"
    end
  end

  def install
    bin.install "pomodorust"
  end

  test do
    assert_match version, shell_output("#{bin}/pomodorust --version")
  end
end
